name:       karasu
version:    2.0.0
license:    MIT
author:     "Krasjet"
maintainer: "Krasjet"
copyright:  "Copyright (c) 2020 Krasjet"

category: Web

description: "A self-hosted remote communication system designed for math discussions."

dependencies:
- pandoc-utils
- libkst
- fl-tr
- base >= 4.7 && < 5
- aeson
- blaze-html
- bytestring
- deepseq
- directory
- doctemplates
- dotenv
- filepath
- fl-tr
- http-types
- monad-logger
- mtl
- pandoc >= 2.7 && < 2.10
- pandoc-types >= 1.20 && < 2
- persistent-template
- persistent-sqlite
- servant-rawm
- resource-pool
- servant
- servant-server
- servant-blaze
- split
- template-haskell
- text
- transformers
- wai
- wai-extra
- wai-app-static
- warp

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src

executables:
  karasu:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - karasu

verbatim:
  cabal-version: ">=2.0"
