name:       karasu
version:    0.1.0.0
license:    MIT
author:     "Krasjet"
maintainer: "Krasjet"
copyright:  "Copyright (c) 2020 Krasjet"

category: Web

description: "A work in progress."

dependencies:
- base >= 4.7 && < 5
- aeson
- base64-bytestring
- blaze-html
- bytestring
- containers
- cryptohash-sha256
- deepseq
- directory
- doctemplates
- dotenv
- filepath
- monad-logger
- mtl
- pandoc >= 2.7 && < 2.10
- pandoc-types >= 1.20 && < 2
- parsec
- persistent-template
- persistent-sqlite
- process
- PyF
- resource-pool
- servant
- servant-server
- servant-blaze
- split
- template-haskell
- text
- transformers
- wai
- wai-extra
- wai-app-static
- warp

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src

executables:
  karasu:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - karasu

verbatim:
  cabal-version: ">=2.0"
