resolver: lts-15.13

packages:
- .
- pandoc-utils/
- fl.tr/
- libkst/

extra-deps:
- github: Krasjet/servant-rawm
  commit: d3908666ef2c54dedb06ad364aecac9d3e7a7aa5
  subdirs:
    - .
    - servant-rawm-server
