resolver: lts-15.13

packages:
- .
- pandoc-utils/
- fl.tr/
- libkst/

extra-deps:
- github: Krasjet/servant-rawm
  commit: e2cb75df39e886c5d188c5798e2adc060f3cc280
  subdirs:
    - servant-rawm
    - servant-rawm-server
