resolver: lts-15.13

packages:
- .
- pandoc-utils/
- fl.tr/
- libkst/

extra-deps:
- github: Krasjet/servant-rawm
  commit: 0e0d6aa0dcceb09c2c6292fa8396cfe3206d4b2f
  subdirs:
    - servant-rawm-api
    - servant-rawm-server
