resolver: lts-14.27

packages:
- .

# several APIs about templates has changed since 2.7, so we need to use the
# latest version
extra-deps:
- pandoc-2.9.2
- HsYAML-0.2.1.0
- doclayout-0.3
- doctemplates-0.8.1
- emojis-0.1
- haddock-library-1.8.0
- jira-wiki-markup-1.0.0
- pandoc-types-1.20
- skylighting-0.8.3.2
- skylighting-core-0.8.3.2
- texmath-0.12.0.1
- regex-pcre-builtin-0.95.1.1.8.43
- regex-base-0.94.0.0

